apiVersion: v1 # versão da API
kind: Service # tipo de recurso, no caso, um Service
metadata: # metadados do recurso
  name: docker-hello-world-svc # nome do recurso
  labels: # labels do recurso
    app: docker-hello-world # label para identificar o svc
spec: # especificação do recurso
  ports:
    - port: 8088
      targetPort: 80
  selector: # seletor para identificar os pods/deployment que esse svc irá expor
    app: nginx # label que identifica o pod/deployment que será exposto
